spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookurtechnician_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:redis://localhost:6379}
      timeout: 5000ms

logging:
  level:
    root: INFO
    com.bookurtechnician: DEBUG
    org.springframework.security: INFO
